### ISSUE TITLE
Use a distance filter so that apps can sleep as much as possible

### ISSUE THREAD

**Issue by dreese** [Electrode-iOS/ELLocation#6]
Using a `distanceFilter` would prevent location updates from being delivered to the app until the device has moved the specified distance. While the GPS system is still active, letting the app sleep when possible can minimize energy use.

In order to support use by multiple teams, with different needs, within a single app at the same time, a distance filter would have to be set based on the client with the need for highest accuracy.

For example, if one client needs `Good` accuracy while another only needs `Coarse`, the distance filter could be set to an appropriate value for `Good`. If both clients only needed `Coarse`, then the distance filter could be set based on that.

Each time a client is added or removed, or an existing client changes its desired accuracy, the distance filter would need to be updated appropriately.

**Comment by dreese** [comment]
Setting the `distanceFilter` to approximately half of the desired accuracy seems to work fairly well. It does allow some updates while the device is stationary that are caused by GPS fluctuations (especially if the desired accuracy is really low). But it also tries to ensure a timely update while the device is moving so that a previous update that was inaccurate can be updated before the device gets too far.

| Desired Accuracy | Distance Filter |
| --- | --- |
| 3km | 1500m |
| 1km | 500m |
| 100m | 50m |
| 10m | 5m |
| Best | 2m |
| Best For Navigation | None |

**Comment by nonsensery** [comment]
@samgrover Want to close this issue, since the PR was merged? :smile:
